# Configuration for the XChange platform
# Schema v1.1
---

assets: # Each asset declaration specifies an asset or related series of assets
    EFM:
        type: DEFAULT
        bookSize: {minPrice: 1.00, maxPrice: 10.00, tickSize: 0.01}
        fillAlgorithm: PRO_RATA
        orderSizeLimit: 100
    EFQ:
        type: DEFAULT
        bookSize: {minPrice: 1.00, maxPrice: 10.00, tickSize: 0.01}
        fillAlgorithm: PRO_RATA
        orderSizeLimit: 100
    EFV:
        type: DEFAULT
        bookSize: {minPrice: 1.00, maxPrice: 10.00, tickSize: 0.01}
        fillAlgorithm: PRO_RATA
        orderSizeLimit: 100
    EFZ:
        type: DEFAULT
        bookSize: {minPrice: 1.00, maxPrice: 10.00, tickSize: 0.01}
        fillAlgorithm: PRO_RATA
        orderSizeLimit: 100



rounds: # Each round declaration specifies the settings for a round
    Case 1:
        assets: [EFM, EFQ, EFV, EFZ]
        limits:
            - {type: ASSET_POSITION, asset: EFM, limit: 1001, liquidationFactor: 1.1, penalty: AUTOLIQ}
            - {type: ASSET_POSITION, asset: EFQ, limit: 1001, liquidationFactor: 1.1, penalty: AUTOLIQ}
            - {type: ASSET_POSITION, asset: EFV, limit: 1001, liquidationFactor: 1.1, penalty: AUTOLIQ}
            - {type: ASSET_POSITION, asset: EFZ, limit: 1001, liquidationFactor: 1.1, penalty: AUTOLIQ}

            - {type: ASSET_POSITION, asset: EFM, limit: 1001, gracePeriod: 15000, penalty: FREEZE}
            - {type: ASSET_POSITION, asset: EFQ, limit: 1001, gracePeriod: 15000, penalty: FREEZE}
            - {type: ASSET_POSITION, asset: EFV, limit: 1001, gracePeriod: 15000, penalty: FREEZE}
            - {type: ASSET_POSITION, asset: EFZ, limit: 1001, gracePeriod: 15000, penalty: FREEZE}
        caseManagers:
            - {program: xchange.case_managers.case1.mm_manager, args: {num_competitors: 1}}
    Pause:
        caseManagers:
            - program: xchange.round_manager


timeline: # Specifies the order in which the rounds are run
    - Case 1

logging:
    frequency: 0.5 # Logging frequency in seconds

resources:
    python: venv/bin/python
    orderManager:
        numThreads: 20 # Use this play with the threads / service. Platform team will optimize this pre-competition
