# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: competitor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='competitor.proto',
  package='edu.uchicago.midwesttrading.xchange',
  syntax='proto3',
  serialized_options=b'B\020CompetitorProtos',
  serialized_pb=b'\n\x10\x63ompetitor.proto\x12#edu.uchicago.midwesttrading.xchange\";\n\x15\x43ompetitorCredentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\tB\x12\x42\x10\x43ompetitorProtosb\x06proto3'
)




_COMPETITORCREDENTIALS = _descriptor.Descriptor(
  name='CompetitorCredentials',
  full_name='edu.uchicago.midwesttrading.xchange.CompetitorCredentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='edu.uchicago.midwesttrading.xchange.CompetitorCredentials.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='edu.uchicago.midwesttrading.xchange.CompetitorCredentials.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['CompetitorCredentials'] = _COMPETITORCREDENTIALS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompetitorCredentials = _reflection.GeneratedProtocolMessageType('CompetitorCredentials', (_message.Message,), {
  'DESCRIPTOR' : _COMPETITORCREDENTIALS,
  '__module__' : 'competitor_pb2'
  # @@protoc_insertion_point(class_scope:edu.uchicago.midwesttrading.xchange.CompetitorCredentials)
  })
_sym_db.RegisterMessage(CompetitorCredentials)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
