# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import competitor_registry_pb2 as competitor__registry__pb2
from . import data_feed_pb2 as data__feed__pb2
from . import order_book_pb2 as order__book__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='exchange.proto',
  package='edu.uchicago.midwesttrading.xchange',
  syntax='proto3',
  serialized_options=b'B\016ExchangeProtos',
  serialized_pb=b'\n\x0e\x65xchange.proto\x12#edu.uchicago.midwesttrading.xchange\x1a\x19\x63ompetitor_registry.proto\x1a\x0f\x64\x61ta_feed.proto\x1a\x10order_book.proto2\xce\x06\n\x0f\x45xchangeService\x12\x95\x01\n\x12RegisterCompetitor\x12>.edu.uchicago.midwesttrading.xchange.RegisterCompetitorRequest\x1a?.edu.uchicago.midwesttrading.xchange.RegisterCompetitorResponse\x12\x91\x01\n\x15StreamExchangeUpdates\x12\x41.edu.uchicago.midwesttrading.xchange.StreamExchangeUpdatesRequest\x1a\x33.edu.uchicago.midwesttrading.xchange.ExchangeUpdate0\x01\x12\x89\x01\n\x0e\x41waitCaseStart\x12:.edu.uchicago.midwesttrading.xchange.AwaitCaseStartRequest\x1a;.edu.uchicago.midwesttrading.xchange.AwaitCaseStartResponse\x12}\n\nPlaceOrder\x12\x36.edu.uchicago.midwesttrading.xchange.PlaceOrderRequest\x1a\x37.edu.uchicago.midwesttrading.xchange.PlaceOrderResponse\x12\x80\x01\n\x0bModifyOrder\x12\x37.edu.uchicago.midwesttrading.xchange.ModifyOrderRequest\x1a\x38.edu.uchicago.midwesttrading.xchange.ModifyOrderResponse\x12\x80\x01\n\x0b\x43\x61ncelOrder\x12\x37.edu.uchicago.midwesttrading.xchange.CancelOrderRequest\x1a\x38.edu.uchicago.midwesttrading.xchange.CancelOrderResponseB\x10\x42\x0e\x45xchangeProtosb\x06proto3'
  ,
  dependencies=[competitor__registry__pb2.DESCRIPTOR,data__feed__pb2.DESCRIPTOR,order__book__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_EXCHANGESERVICE = _descriptor.ServiceDescriptor(
  name='ExchangeService',
  full_name='edu.uchicago.midwesttrading.xchange.ExchangeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=118,
  serialized_end=964,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterCompetitor',
    full_name='edu.uchicago.midwesttrading.xchange.ExchangeService.RegisterCompetitor',
    index=0,
    containing_service=None,
    input_type=competitor__registry__pb2._REGISTERCOMPETITORREQUEST,
    output_type=competitor__registry__pb2._REGISTERCOMPETITORRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamExchangeUpdates',
    full_name='edu.uchicago.midwesttrading.xchange.ExchangeService.StreamExchangeUpdates',
    index=1,
    containing_service=None,
    input_type=data__feed__pb2._STREAMEXCHANGEUPDATESREQUEST,
    output_type=data__feed__pb2._EXCHANGEUPDATE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AwaitCaseStart',
    full_name='edu.uchicago.midwesttrading.xchange.ExchangeService.AwaitCaseStart',
    index=2,
    containing_service=None,
    input_type=competitor__registry__pb2._AWAITCASESTARTREQUEST,
    output_type=competitor__registry__pb2._AWAITCASESTARTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PlaceOrder',
    full_name='edu.uchicago.midwesttrading.xchange.ExchangeService.PlaceOrder',
    index=3,
    containing_service=None,
    input_type=order__book__pb2._PLACEORDERREQUEST,
    output_type=order__book__pb2._PLACEORDERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ModifyOrder',
    full_name='edu.uchicago.midwesttrading.xchange.ExchangeService.ModifyOrder',
    index=4,
    containing_service=None,
    input_type=order__book__pb2._MODIFYORDERREQUEST,
    output_type=order__book__pb2._MODIFYORDERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CancelOrder',
    full_name='edu.uchicago.midwesttrading.xchange.ExchangeService.CancelOrder',
    index=5,
    containing_service=None,
    input_type=order__book__pb2._CANCELORDERREQUEST,
    output_type=order__book__pb2._CANCELORDERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXCHANGESERVICE)

DESCRIPTOR.services_by_name['ExchangeService'] = _EXCHANGESERVICE

# @@protoc_insertion_point(module_scope)
